-- EXTENSION TO GENERATE UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- CREATE 3 TABLES - IF NOT EXISTS

-- TARGETGROUP table
CREATE TABLE IF NOT EXISTS TARGETGROUP (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    LABEL TEXT NOT NULL UNIQUE
);

-- TARGET table
CREATE TABLE IF NOT EXISTS TARGET (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    GROUPID UUID NOT NULL REFERENCES TARGETGROUP(ID) ON DELETE CASCADE,
    ENDPOINT TEXT NOT NULL UNIQUE,
    INTERVAL INTERVAL NOT NULL,
    LAST_RUN TIMESTAMP DEFAULT NULL,
    NEXT_RUN TIMESTAMP DEFAULT NULL
);

-- LOG table
CREATE TABLE IF NOT EXISTS LOG (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ENDPOINTID UUID NOT NULL REFERENCES TARGET(ID) ON DELETE CASCADE,
    GROUPID UUID NOT NULL REFERENCES TARGETGROUP(ID) ON DELETE CASCADE,

    -- Response
    STATUSCODE INT NOT NULL,
    RESPONSETIME INTERVAL NOT NULL,
    RUN_AT TIMESTAMP NOT NULL
);