-- TARGET table insert query
INSERT INTO TARGET (GROUPID, ENDPOINT, INTERVAL)
SELECT 
    (SELECT ID FROM TARGETGROUP WHERE LABEL=$1),
    $2, 
    $3
ON CONFLICT (ENDPOINT) DO UPDATE SET
    GROUPID = EXCLUDED.GROUPID,
    INTERVAL = EXCLUDED.INTERVAL;
