-- EXTENSION TO GENERATE UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- CREATE 3 TABLES - IF NOT EXISTS

-- TARGETGROUP table
CREATE TABLE IF NOT EXISTS TARGETGROUP (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    LABEL TEXT NOT NULL UNIQUE
);

-- TARGET table
CREATE TABLE IF NOT EXISTS TARGET (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ENDPOINT TEXT NOT NULL UNIQUE,
    INTERVAL TEXT NOT NULL,
    GROUPID UUID REFERENCES TARGETGROUP(ID) ON DELETE CASCADE 
);

-- LOG table
CREATE TABLE IF NOT EXISTS LOG (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ENDPOINTID UUID REFERENCES TARGET(ID),
    GROUPID UUID REFERENCES TARGETGROUP(ID),

    -- Response
    STATUSCODE INT NOT NULL,
    RESPONSETIME TEXT NOT NULL,
    LAST_PING_AT TIMESTAMP NOT NULL,
    NEXT_PING_AT TIMESTAMP NOT NULL
);