-- EXTENSION TO GENERATE UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- CREATE 3 TABLES - IF NOT EXISTS

-- TARGETGROUP table
CREATE TABLE IF NOT EXISTS TARGETGROUP (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    LABEL TEXT NOT NULL UNIQUE
);

-- TARGET table
CREATE TABLE IF NOT EXISTS TARGET (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ENDPOINT TEXT NOT NULL UNIQUE,
    INTERVAL TEXT NOT NULL,
    GROUPID UUID REFERENCES TARGETGROUP(ID) 
)

-- LOG table
-- CREATE TABLE IF NOT EXISTS LOG ()