-- EXTENSION TO GENERATE UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- CREATE 3 TABLES - IF NOT EXISTS

-- TARGETGROUP
CREATE TABLE IF NOT EXISTS TARGETGROUP (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    LABEL TEXT NOT NULL UNIQUE,
)